# Config file for labeler to auto label PRs
documentation:
  - README.md
  - docs/**/*.md

config:
  - backend/config/**/*

db:
  - backend/db/**/*
  - backend/models/**/*

UI/UX:
  - frontend/build/**/*.css
  - frontend/build/**/*.html

automation:
  - .github/**/*.yml

npm packages:
  - **/package.json
  - **/package-lock.json

models:
  - backend/models/*
  - backend/models/**/*

build:
  - frontend/build/*
  - frontend/build/**/*

routes:
  - backend/routes/*
  - backend/routes/**/*

frontend:
  - frontend/**/*

backend:
  - backend/**/*

components:
  - frontend/src/components/**/*.js

